### PR TITLE
Remove console.log() call

### PR DESCRIPTION
**Pull request by Toflar**
Seems like this is a leftover of the development process? :-) It fills up my console ;-)

### CODE REVIEW

**Comment by qzminski** [comment]
+1

**Comment by cferdinandi** [comment]
Good catch! I think I was in "move fast and break things" mode when I last pushed code to this project.

Before I can commit this, the build needs to get run so that the two distribution copies are updated as well. Did you want to do this, or would you prefer I do it?

**Comment by Toflar** [comment]
> Before I can commit this, the build needs to get run so that the two distribution copies are updated as well. Did you want to do this, or would you prefer I do it?

Ah, well it was just a quick fix PR using the GitHub edit feature ;-) So I don't mind if you do it as I assume you already know what to run ;-) Go ahead, pls :-)

**Comment by cferdinandi** [comment]
Closing since I've deprecated the plugin.

**Pull request closed without merging**
